### ISSUE TITLE
newlib linking errors

### ISSUE THREAD

**Issue by WDrijver** [ddraig68k/m68k-elf-toolchain#3]
Hi, first of all thank you very much for your work on GCC 12.2 based toolchain for m68k-elf target.

I have some strange errors (see below) on undefined references in "re-entry routines" on compiled libc.a from newlib.
Same issue occurs on two independent builds using GCC12.2 and m68k-elf and m68k-amiga-elf targets.
First install is a clean version based on your make and second install is my own bash shell script.

Any thoughts? Thanks for your help.

willem@Compiler2:~/Dev/m68k-elf-toolchain/output$ bin/m68k-elf-gcc hello.c
/home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/bin/ld: warning: cannot find entry symbol _start; defaulting to 0000000080000080
/home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/bin/ld: /home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/lib/libc.a(lib_a-sbrkr.o): in function `_sbrk_r':
/home/willem/Dev/m68k-elf-toolchain/projects/newlib-cygwin/newlib/libc/reent/sbrkr.c:51: undefined reference to `sbrk'
/home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/bin/ld: /home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/lib/libc.a(lib_a-writer.o): in function `_write_r':
/home/willem/Dev/m68k-elf-toolchain/projects/newlib-cygwin/newlib/libc/reent/writer.c:49: undefined reference to `write'
/home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/bin/ld: /home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/lib/libc.a(lib_a-closer.o): in function `_close_r':
/home/willem/Dev/m68k-elf-toolchain/projects/newlib-cygwin/newlib/libc/reent/closer.c:47: undefined reference to `close'
/home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/bin/ld: /home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/lib/libc.a(lib_a-lseekr.o): in function `_lseek_r':
/home/willem/Dev/m68k-elf-toolchain/projects/newlib-cygwin/newlib/libc/reent/lseekr.c:49: undefined reference to `lseek'
/home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/bin/ld: /home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/lib/libc.a(lib_a-readr.o): in function `_read_r':
/home/willem/Dev/m68k-elf-toolchain/projects/newlib-cygwin/newlib/libc/reent/readr.c:49: undefined reference to `read'
/home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/bin/ld: /home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/lib/libc.a(lib_a-fstatr.o): in function `_fstat_r':
/home/willem/Dev/m68k-elf-toolchain/projects/newlib-cygwin/newlib/libc/reent/fstatr.c:55: undefined reference to `fstat'
/home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/bin/ld: /home/willem/Dev/m68k-elf-toolchain/output/lib/gcc/m68k-elf/10.4.1/../../../../m68k-elf/lib/libc.a(lib_a-isattyr.o): in function `_isatty_r':
/home/willem/Dev/m68k-elf-toolchain/projects/newlib-cygwin/newlib/libc/reent/isattyr.c:52: undefined reference to `isatty'
